### PR TITLE
Bevy 0.6

### PR DESCRIPTION
**Pull request by sdfgeoff**
It builds, but the resulting meshes are all messed up.

Also, the python logging changes should be in a different PR [EDIT: moved and merged]

### CODE REVIEW

**Comment by sdfgeoff** [comment]
Mesh issue is most likely https://github.com/bevyengine/bevy/issues/3604

**Comment by sdfgeoff** [comment]
Physics now works in the example file, but I can't find equivalents for the `extra_mass or` `extra_inertia fields`

**Comment by sdfgeoff** [comment]
@thechubbypanda If you could give this code a test and review that would be amazing.

**Comment by thechubbypanda** [comment]
@sdfgeoff I'll try if I have time after work :)

**Comment by thechubbypanda** [comment]
@sdfgeoff Just had a look, works nicely on my machine :ok_hand:

**Comment by sdfgeoff** [comment]
Thanks for testing!

**Pull request merged**
